version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "daily"
    automerge: true
  - package-ecosystem: "npm"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
    automerge: true
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    automerge: true
