apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: trading-assistant
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./kube-infrastructure
  sourceRef:
    kind: GitRepository
    name: trading-assistant
    namespace: flux-system
