apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: darwinex-client
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: terraform-updates
  url: https://github.com/willhumphreys/darwinex-client