name: Maven Build

defaults:
  run:
    working-directory: backend
on:
  push:
    branches: [ main ]
    paths:
      - backend/**
  pull_request:
    branches: [ main ]
    paths:
      - backend/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven shorttest
        run: mvn -B verify -Dprofile.active=shorttest --file pom.xml
      - name: Build with Maven longtest
        run: mvn -B verify -Dprofile.active=longtest --file pom.xml
