name: frontend-build
defaults:
  run:
    working-directory: frontend
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  build-docker-image-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build, tag, and push docker image to GitHub Packages
        env:
          GHCR_REGISTRY: ghcr.io
          GHCR_REPOSITORY: willhumphreys/trading-assistant
          IMAGE_TAG: frontend-${{ github.sha }}
        run: |
          docker build -t $GHCR_REGISTRY/$GHCR_REPOSITORY:$IMAGE_TAG -t $GHCR_REGISTRY/$GHCR_REPOSITORY:latest -f frontend/Dockerfile frontend
          docker push $GHCR_REGISTRY/$GHCR_REPOSITORY:$IMAGE_TAG
          docker push $GHCR_REGISTRY/$GHCR_REPOSITORY:frontend-latest