name: test-frontend
defaults:
  run:
    working-directory: frontend
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
