name: deploy-tradingAssistant
defaults:
  run:
    working-directory: infrastructure
on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
  pull_request:
    branches: [ main ]
    paths:
      - infrastructure/**
  workflow_dispatch: { }
jobs:
  deploy:
    name: Deploy CDK stacks to test
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::573591465159:role/gitHubDeployRole
          aws-region: eu-central-1
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        env:
          GITHUB_BRANCH: main
      - name: CDK synth
        env:
          GITHUB_BRANCH: main
        run: npx cdk synth TradingAssistant
      - name: CDK deploy
        env:
          GITHUB_BRANCH: main
        run: npx cdk deploy TradingAssistant
