name: build-kube-infrastructure
defaults:
  run:
    working-directory: kube-infrastructure
on:
  push:
    branches:
      - main
    paths:
      - kube-infrastructure/**
  pull_request:
    branches: [ main ]
    paths:
      - kube-infrastructure/**
  workflow_dispatch: { }
jobs:
  synth:
    name: Build and Synth Terraform CDK Stacks
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: npm install
      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli
      - name: Run tests
        run: npm test
      - name: CDK synth TradingAssistant
        run: npx cdktf synth
      - name: Configure Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Create New Branch
        run: |
          git checkout -b generated-cdktf-out-${{ github.run_id }}

      - name: Commit Generated Files
        run: |
          git add cdktf.out
          git commit -m "Update cdktf.out - ${{ github.run_id }}"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated-cdktf-out-${{ github.run_id }}